import { useEffect, useMemo, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { useNavigate } from 'react-router';
import { PayPalProvider, PayPalOneTimePaymentButton } from '@paypal/react-paypal-js/sdk-v6';
import { createCodOrder, createPaypalOrder, capturePaypalOrder, cancelPaypalOrder } from '../redux/thunks/orderThunks';
import { clearLocalCart } from '../redux/slices/cartSlice';
import Loader from '../components/Loader';

const money = n => `₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
export default function Checkout(){
 const dispatch=useDispatch(); const navigate=useNavigate(); const {items}=useSelector(s=>s.cart); const {user}=useSelector(s=>s.auth); const {current,paymentLoading,loading,error}=useSelector(s=>s.orders); const [paypalConfig,setPaypalConfig]=useState(null); const [form,setForm]=useState({name:user?.name||'',phone:user?.phone||'',street:user?.address?.street||'',city:user?.address?.city||'',state:user?.address?.state||'',postalCode:user?.address?.postalCode||'',country:user?.address?.country||'India'});
 const address=useMemo(()=>Object.fromEntries(Object.entries(form).map(([key,value])=>[key,String(value||'').trim()])),[form]); const addressComplete=Object.values(address).every(Boolean); const total=items.reduce((sum,i)=>sum+i.price*i.quantity,0);
 useEffect(()=>{if(!items.length&&!current)navigate('/cart',{replace:true})},[items.length,current,navigate]);
 useEffect(()=>{let mounted=true;fetch(`${import.meta.env.VITE_API_URL||'http://localhost:5000/api/v1'}/paypal/config`,{credentials:'include'}).then(r=>r.json()).then(r=>{if(mounted)setPaypalConfig(r.data)}).catch(()=>{});return()=>{mounted=false}},[]);
 useEffect(()=>{if(current){navigate('/orders',{replace:true})}},[current,navigate]);
 const submitCod=async e=>{e.preventDefault();if(!addressComplete)return;await dispatch(createCodOrder({shippingAddress:address})).unwrap();dispatch(clearLocalCart())};
 if(!items.length)return <Loader label="Checking cart..."/>;
 const input=(k,p)=><input required value={form[k]} placeholder={p} onChange={e=>setForm(prev=>({...prev,[k]:e.target.value}))} className="w-full rounded-xl border border-slate-200 px-4 py-3"/>;
 const paypal=paypalConfig?.clientId?<PayPalProvider clientId={paypalConfig.clientId} environment={paypalConfig.environment} currency={paypalConfig.currency} components={["paypal-payments"]} pageType="checkout"><PayPalOneTimePaymentButton type="checkout" disabled={paymentLoading||!addressComplete} createOrder={async()=>{const result=await dispatch(createPaypalOrder({shippingAddress:address})).unwrap();return {orderId:result.paypalOrderId}}} onApprove={async({orderId})=>{await dispatch(capturePaypalOrder(orderId)).unwrap();dispatch(clearLocalCart())}} onCancel={async({orderId})=>{if(orderId)await dispatch(cancelPaypalOrder(orderId))}} onError={e=>console.error('PayPal error',e)}/></PayPalProvider>:<div className="rounded-xl bg-amber-50 p-4 text-sm text-amber-800">PayPal is disabled until the backend client ID is configured.</div>;
 return <section className="space-y-6"><div><p className="text-sm font-semibold uppercase tracking-widest text-indigo-600">Secure checkout</p><h1 className="text-3xl font-black">Complete your order</h1><p className="mt-1 text-slate-500">Final prices and stock are calculated on the server.</p></div>{error&&<div className="rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}<div className="grid gap-6 lg:grid-cols-[1fr_380px]"><form onSubmit={submitCod} className="space-y-5 rounded-3xl border border-slate-200 bg-white p-6 lg:p-8"><h2 className="text-xl font-black">Delivery details</h2><div className="grid gap-4 md:grid-cols-2">{input('name','Full name')}{input('phone','Phone')}{input('street','Street address')}{input('city','City')}{input('state','State')}{input('postalCode','Postal code')}{input('country','Country')}</div><button disabled={loading} className="w-full rounded-xl bg-slate-900 px-4 py-3.5 font-semibold text-white disabled:opacity-50">{loading?'Placing order...':'Cash on Delivery'}</button></form><aside className="h-fit space-y-5 rounded-3xl border border-slate-200 bg-white p-6"><div><h2 className="text-xl font-black">Pay with PayPal</h2><p className="mt-1 text-sm leading-6 text-slate-500">PayPal creates and captures the payment through the server. The browser never controls the final amount.</p></div>{paypal}<div className="border-t pt-5"><div className="space-y-3">{items.map(i=><div key={i.productId} className="flex items-center gap-3"><img src={i.image} alt="" className="h-12 w-12 rounded-lg object-cover"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{i.name}</p><p className="text-xs text-slate-500">{i.quantity} × {money(i.price)}</p></div><span className="font-semibold">{money(i.price*i.quantity)}</span></div>)}</div><div className="mt-5 flex justify-between border-t pt-4 text-lg font-black"><span>Total</span><span>{money(total)}</span></div><p className="mt-2 text-xs text-slate-400">PayPal uses the configured server-side currency conversion when enabled.</p></div></aside></div></section>;
}
