import { useState } from 'react';
import { Mail, Send, ShieldCheck } from 'lucide-react';
import api from '../api/axiosInstance';
import { useToast } from '../components/ToastProvider';
export default function Contact(){
 const [form,setForm]=useState({name:'',email:'',subject:'',message:''}); const [state,setState]=useState({loading:false,error:'',message:''}); const { showToast } = useToast();
 const submit=async e=>{e.preventDefault();setState({loading:true,error:'',message:''});try{const {data}=await api.post('/contact',form);setState({loading:false,error:'',message:data.message});showToast(data.message || 'Message sent.');setForm({name:'',email:'',subject:'',message:''});}catch(err){const message=err.response?.data?.message||'Unable to send message';setState({loading:false,error:message,message:''});showToast(message,'error')}};
 const input=(key,placeholder,type='text')=><input required type={type} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-50"/>;
 return <section className="grid gap-8 lg:grid-cols-[360px_1fr]"><aside className="rounded-3xl bg-slate-950 p-8 text-white"><Mail size={28} className="text-indigo-300"/><h1 className="mt-6 text-3xl font-black">Let’s talk</h1><p className="mt-3 leading-7 text-slate-300">Questions about products, payments, orders or account access? Send a message to the support team.</p><div className="mt-10 flex items-center gap-3 text-sm text-slate-300"><ShieldCheck size={18} className="text-emerald-400"/>Messages are validated and protected.</div></aside><form onSubmit={submit} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm lg:p-8"><h2 className="text-2xl font-black">Contact support</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{input('name','Your name')}{input('email','Email address','email')}{input('subject','Subject')}<textarea required minLength={10} maxLength={3000} rows="7" value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="How can we help?" className="rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-50 md:col-span-2"/></div>{state.error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{state.error}</p>}{state.message&&<p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{state.message}</p>}<button disabled={state.loading} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white disabled:opacity-50"><Send size={17}/>{state.loading?'Sending...':'Send message'}</button></form></section>;
}
