import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router';
import { Heart, ShoppingCart, Star, ShieldCheck } from 'lucide-react';
import { useDispatch, useSelector } from 'react-redux';
import { fetchProductById } from '../redux/thunks/productThunks';
import { addCartItem } from '../redux/thunks/cartThunks';
import { addWishlist, removeWishlist } from '../redux/thunks/wishlistThunks';
import Loader from '../components/Loader';
import ErrorMessage from '../components/ErrorMessage';
export default function ProductDetail(){
 const {productId}=useParams(); const dispatch=useDispatch(); const navigate=useNavigate(); const {current:product,loading,error}=useSelector(s=>s.products); const auth=useSelector(s=>s.auth); const saved=useSelector(s=>s.wishlist.items.some(i=>i._id===productId)); const [qty,setQty]=useState(1);
 useEffect(()=>{dispatch(fetchProductById(productId))},[dispatch,productId]);
 const add=()=>{if(!auth.isAuthenticated){navigate('/login',{state:{from:`/products/${productId}`}});return;}dispatch(addCartItem({productId,quantity:qty}))};
 const toggle=()=>{if(!auth.isAuthenticated){navigate('/login',{state:{from:`/products/${productId}`}});return;}dispatch(saved?removeWishlist(productId):addWishlist(productId))};
 if(loading)return <Loader label="Loading product..."/>; if(error)return <ErrorMessage message={error} onRetry={()=>dispatch(fetchProductById(productId))}/>; if(!product)return null;
 return <div className="space-y-10"><div className="grid gap-10 lg:grid-cols-[1.05fr_.95fr]"><div className="overflow-hidden rounded-[2rem] bg-slate-100"><img src={product.image} alt={product.name} className="aspect-square h-full w-full object-cover"/></div><div className="flex flex-col justify-center"><Link to="/" className="text-sm font-semibold text-indigo-600">← Back to products</Link><div className="mt-5 flex items-center justify-between gap-4"><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold capitalize text-indigo-700">{product.category}</span><button onClick={toggle} className={`rounded-full border p-3 ${saved?'border-rose-200 bg-rose-50 text-rose-600':'border-slate-200 bg-white text-slate-600'}`}><Heart size={19} fill={saved?'currentColor':'none'}/></button></div><h1 className="mt-5 text-4xl font-black tracking-tight">{product.name}</h1><div className="mt-4 flex items-center gap-2 text-amber-500"><Star size={18} fill="currentColor"/>{Number(product.ratings||0).toFixed(1)} <span className="text-sm text-slate-400">({product.numReviews||0} reviews)</span></div><p className="mt-6 text-4xl font-black">₹{product.price.toLocaleString('en-IN')}</p><p className="mt-5 leading-8 text-slate-600">{product.description}</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Brand</p><p className="mt-1 font-semibold">{product.brand||'—'}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Availability</p><p className="mt-1 font-semibold">{product.stock>0?`${product.stock} in stock`:'Out of stock'}</p></div></div><div className="mt-7 flex gap-3"><div className="flex items-center rounded-xl border border-slate-200"><button disabled={qty<=1} onClick={()=>setQty(q=>q-1)} className="px-4 py-3 disabled:opacity-30">−</button><span className="w-10 text-center font-semibold">{qty}</span><button disabled={qty>=Math.min(99,product.stock)} onClick={()=>setQty(q=>q+1)} className="px-4 py-3 disabled:opacity-30">+</button></div><button disabled={!product.stock} onClick={add} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white disabled:opacity-40"><ShoppingCart size={18}/>Add to cart</button></div><div className="mt-6 flex items-center gap-2 text-sm text-slate-500"><ShieldCheck size={18} className="text-emerald-600"/>Secure session, server-side cart and verified payment flow.</div></div></div></div>;
}
