import { useEffect } from 'react';
import { BarChart3, Boxes, IndianRupee, ShoppingBag, Users, AlertTriangle, ArrowRight } from 'lucide-react';
import { Link } from 'react-router';
import { useDispatch, useSelector } from 'react-redux';
import { fetchAdminDashboard } from '../../redux/thunks/adminThunks';
import Loader from '../../components/Loader';
const money = n => `₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
export default function AdminDashboard(){
 const dispatch=useDispatch(); const {stats,loading,error}=useSelector(s=>s.admin); useEffect(()=>{dispatch(fetchAdminDashboard())},[dispatch]);
 if(loading&&!stats) return <Loader label="Loading admin dashboard..."/>;
 if(error&&!stats) return <div className="rounded-2xl bg-red-50 p-6 text-red-700">{error}</div>;
 const cards=[['Revenue',money(stats?.revenue),IndianRupee,'from-indigo-600 to-violet-600'],['Orders',stats?.orders||0,ShoppingBag,'from-slate-800 to-slate-900'],['Customers',stats?.customers||0,Users,'from-emerald-600 to-teal-600'],['Products',stats?.products||0,Boxes,'from-amber-500 to-orange-600']];
 return <section className="space-y-8"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold uppercase tracking-widest text-indigo-600">Management console</p><h1 className="text-3xl font-black">Admin Dashboard</h1><p className="mt-1 text-slate-500">Monitor sales, customers, inventory and order operations.</p></div><div className="flex gap-2"><Link to="/admin/products" className="rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold">Products</Link><Link to="/admin/customers" className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Customers</Link></div></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,Icon,gradient])=><div key={label} className={`rounded-2xl bg-gradient-to-br ${gradient} p-5 text-white shadow-lg`}><Icon size={22} className="opacity-90"/><p className="mt-6 text-sm text-white/75">{label}</p><p className="mt-1 text-3xl font-black">{value}</p></div>)}</div>
 <div className="grid gap-6 lg:grid-cols-[1fr_360px]"><div className="rounded-2xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-black">Recent orders</h2><p className="text-sm text-slate-500">Latest customer activity</p></div><Link to="/admin/orders" className="text-sm font-semibold text-indigo-600">View all</Link></div><div className="divide-y">{(stats?.recentOrders||[]).map(o=><div key={o._id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex -space-x-2">{o.items?.slice(0,3).map(i=><img key={`${o._id}-${i.name}`} src={i.image||i.product?.image} alt="" className="h-10 w-10 rounded-full object-cover ring-2 ring-white"/>)}</div><div><p className="font-semibold">{o.user?.name||'Customer'}</p><p className="text-xs text-slate-500">#{o._id.slice(-8).toUpperCase()} · {new Date(o.createdAt).toLocaleDateString()}</p></div></div><div className="text-left sm:text-right"><p className="font-black">{money(o.totalPrice)}</p><p className="text-xs capitalize text-slate-500">{o.paymentStatus} · {o.orderStatus}</p></div></div>)}{!(stats?.recentOrders||[]).length&&<div className="p-10 text-center text-slate-500">No orders yet.</div>}</div></div>
 <aside className="space-y-4"><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-3"><AlertTriangle className="text-amber-500" size={22}/><div><p className="font-bold">Low stock</p><p className="text-sm text-slate-500">{stats?.lowStock||0} product(s) at or below 5 units</p></div></div><Link to="/admin/products" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-indigo-600">Review inventory <ArrowRight size={16}/></Link></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-3"><BarChart3 className="text-indigo-600" size={22}/><div><p className="font-bold">Pending operations</p><p className="text-sm text-slate-500">{stats?.pendingOrders||0} orders need attention</p></div></div><Link to="/admin/orders" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-indigo-600">Open orders <ArrowRight size={16}/></Link></div></aside></div>
 </section>;
}
