import { useEffect, useState } from 'react';
import { Eye, Search, UserCheck, UserX } from 'lucide-react';
import { useDispatch, useSelector } from 'react-redux';
import { fetchCustomers, fetchCustomerDetails, updateCustomerStatus } from '../../redux/thunks/adminThunks';
import Loader from '../../components/Loader';

const money = (n) => `₹${Number(n || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;

export default function CustomerManagement() {
  const dispatch = useDispatch();
  const { customers, pagination, selectedCustomer, loading, error } = useSelector((s) => s.admin);
  const [search, setSearch] = useState('');
  useEffect(() => { dispatch(fetchCustomers({ page: 1, limit: 20 })); }, [dispatch]);
  const doSearch = (e) => { e.preventDefault(); dispatch(fetchCustomers({ search, page: 1, limit: 20 })); };

  return <section className="space-y-6">
    <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold uppercase tracking-widest text-indigo-600">Administration</p><h1 className="text-3xl font-black">Customers</h1><p className="mt-1 text-slate-500">View customer profiles, order activity and account status.</p></div><form onSubmit={doSearch} className="flex gap-2"><div className="relative"><Search size={18} className="absolute left-3 top-3.5 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer" className="w-72 rounded-xl border border-slate-200 bg-white py-3 pl-10 pr-4"/></div><button className="rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white">Search</button></form></div>
    {error && <div className="rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}
    {loading && !customers.length ? <Loader label="Loading customers..."/> : <div className="grid gap-6 xl:grid-cols-[1fr_380px]"><div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="border-b bg-slate-50"><tr><th className="p-4">Customer</th><th className="p-4">Orders</th><th className="p-4">Spent</th><th className="p-4">Status</th><th className="p-4">Actions</th></tr></thead><tbody>{customers.map(c=><tr key={c._id} className="border-b last:border-0"><td className="p-4"><div><p className="font-semibold">{c.name}</p><p className="text-xs text-slate-500">{c.email}</p><p className="text-xs text-slate-400">{c.phone || 'No phone'}</p></div></td><td className="p-4">{c.orderCount}</td><td className="p-4 font-semibold">{money(c.totalSpent)}</td><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${c.isActive?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{c.isActive?'Active':'Disabled'}</span></td><td className="p-4"><div className="flex gap-2"><button onClick={()=>dispatch(fetchCustomerDetails(c._id))} className="rounded-lg border px-3 py-2"><Eye size={16}/></button><button title={c.isActive?'Disable':'Enable'} onClick={()=>dispatch(updateCustomerStatus({id:c._id,isActive:!c.isActive}))} className="rounded-lg border px-3 py-2">{c.isActive?<UserX size={16}/>:<UserCheck size={16}/>}</button></div></td></tr>)}</tbody></table></div>
    <aside className="h-fit rounded-2xl border border-slate-200 bg-white p-6">{selectedCustomer ? <><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-widest text-indigo-600">Customer details</p><h2 className="mt-1 text-xl font-black">{selectedCustomer.customer.name}</h2><p className="text-sm text-slate-500">{selectedCustomer.customer.email}</p></div><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700">{selectedCustomer.stats.orders} orders</span></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Total spent</p><p className="mt-1 text-lg font-black">{money(selectedCustomer.stats.totalSpent)}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Last login</p><p className="mt-1 text-sm font-semibold">{selectedCustomer.customer.lastLoginAt?new Date(selectedCustomer.customer.lastLoginAt).toLocaleString():'—'}</p></div></div><div className="mt-6"><p className="font-bold">Recent orders</p><div className="mt-3 space-y-3">{selectedCustomer.orders.slice(0,8).map(o=><div key={o._id} className="rounded-xl border border-slate-200 p-3"><div className="flex items-center justify-between"><span className="text-sm font-semibold">#{o._id.slice(-8).toUpperCase()}</span><span className="text-sm font-bold">{money(o.totalPrice)}</span></div><p className="mt-1 text-xs capitalize text-slate-500">{o.orderStatus} · {o.paymentStatus}</p><div className="mt-2 flex gap-2 overflow-x-auto">{o.items?.map(i=><img key={`${o._id}-${i.product?._id||i.name}`} src={i.image || i.product?.image} alt={i.name} className="h-12 w-12 rounded-lg object-cover ring-1 ring-slate-200"/>)}</div></div>)}</div></div></> : <div className="py-16 text-center text-slate-500">Select a customer to inspect details.</div>}</aside></div>}
  </section>;
}
